### ISSUE TITLE
can not run in idea IDE under windows

### ISSUE THREAD

**Issue by sunlingfeng-daren** [dobromyslov/sencha-extjs-maven#3]
when i run it using idea maven plugin,can not find Ruby ,but it can run properly under command!

**Comment by dobromyslov** [comment]
Thank you, mr. Sunlingfeng. I'll try to update this project to the current version of extjs and cmd.

**Comment by dobromyslov** [comment]
IntelliJ Idea does not work properly with operating system environment variables. I'm looking for the solution. Meanwhile I've just updated this project to ExtJS 5.1 and Sencha Cmd 5.1.

**Comment by sunlingfeng-daren** [comment]
Thank for your reply.I also find this link http://www.sencha.com/forum/showthread.php?268087-Calling-Sencha-CMD-in-Maven-compile-Cannot-find-com-sencha-ant-antlib.xml&p=1029277&viewfull=1#post1029277. It create same problem.as following:com.sencha.exceptions.ExProcess: Failed creating background process

**Comment by dobromyslov** [comment]
Maybe this could help http://docs.sencha.com/cmd/5.x/intro_to_cmd.html#Cannot_find_Ruby

**Comment by dobromyslov** [comment]
Hope that workaround has helped.
